from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class CopilotChatRequest(BaseModel):
    message: str = Field(..., description="Conversational query from the resource manager.")
    session_id: str = Field(default="default", description="Conversation session unique identifier.")

class CopilotChatResponse(BaseModel):
    response: str = Field(..., description="Markdown response text generated by the Copilot.")
    detected_intent: str = Field(..., description="Intent classified for the message.")
    intent_confidence: float = Field(..., description="Confidence of classified intent.")
    suggested_questions: List[str] = Field(default_factory=list, description="Follow-up questions recommended based on context.")
    executed_tools: List[str] = Field(default_factory=list, description="List of internal tools executed for this request.")

class CopilotExplainRequest(BaseModel):
    employee_id: str = Field(..., description="Employee ID to explain recommendation for.")
    project_id: str = Field(..., description="Project ID to explain recommendation for.")

class CopilotExplainResponse(BaseModel):
    explanation: str = Field(...)

class ChatMessage(BaseModel):
    role: str  # user or assistant
    content: str
    timestamp: float

class ConversationHistoryResponse(BaseModel):
    session_id: str
    history: List[ChatMessage]
